-- Build 260 — current Startup catalog, evidence relevance, and execution cycle
-- Apply after the Build 259 vehicle-size migration. Historical evidence is retained; retired process rows are only deactivated.
update public.app_startup_process_items set is_active=false, updated_at=now() where process_key in ('deploy-239','migration-237','migration-238','migration-239','migration-240','startup-single-interface','media-derivatives','markdown-retirement');
insert into public.app_startup_process_items(process_key,sort_order,category,severity,title,why_text,locations,instructions,done_when,action_route,evidence_key,source_build,is_active) values
('deploy-260',1,'Deployment and UI health','blocker','Deploy Build 260 and verify current assets, cache and Startup Command Center','A mixed deployment can make current pages execute historical startup scripts or service-worker caches. Build 260 makes deployed-build parity a current acceptance requirement rather than asking staff to re-approve old build migrations.','["Cloudflare Pages \u2192 Deployments","/admin-startup-guide.html#ui-health","/admin-ui-health.html","Browser DevTools \u2192 Network and Application"]'::jsonb,'["Deploy the complete Build 260 Pages and Functions output to preview/staging.","Hard-refresh /admin-startup-guide and run Check cache & build.","Confirm the expected startup script build, fetched build and active rosie-app service-worker cache all report Build 260.","Open /admin-ui-health and run the current route scan at desktop and phone widths.","Confirm there is no recurring 404/500/1102 on required startup, media or booking APIs.","Record only the deployment ID/date and safe outcome in evidence; do not store credentials or customer data."]'::jsonb,'The current deployment, startup script, UI scanner and service-worker cache all identify Build 260, required routes pass, and no historical cache/build mismatch remains.','/admin-startup-guide.html#ui-health','deploy_260',260,true),
('photo-studio-sync-260',40,'Media and public proof','high','Accept the bounded Photo Studio R2 sync and assignment reset workflow','The public image library is now large enough that one Worker invocation must not scan and patch the entire library. Build 260 synchronizes one cursor-bounded page from one approved R2 folder per invocation and batches database upserts while preserving explicit placements.','["/admin-photo-studio.html","Cloudflare Workers Logs","Supabase \u2192 app_media_library","Supabase \u2192 app_media_assignments"]'::jsonb,'["Open Photo Studio normally and confirm it loads from the managed database without scanning R2.","Press Sync approved R2 photos once and confirm each approved folder completes without Too many subrequests or Error 1102.","Assign one harmless photo to two different test placements and confirm both placements remain visible.","Reset one of those placements to default and confirm only that placement returns to its authored/default image.","Confirm the second placement still uses the selected photo and the photo remains in the library.","Remove the remaining test assignment or restore the original authored assignment before finishing."]'::jsonb,'Approved-folder sync completes within Worker limits, one photo can safely serve multiple placements, and Reset to default removes only the selected explicit placement.','/admin-photo-studio.html','photo_sync_260',260,true),
('vehicle-size-review-259',41,'Booking and customer communication','blocker','Accept the Build 259 uncertain vehicle-size review and customer correction flow','Bookings with an uncertain vehicle classification must not silently charge the wrong package size. Staff need to verify the selected size or send a secure correction that the customer can confirm or cancel.','["sql/2026-08-13_build259_vehicle_size_review.sql","/admin-booking.html","/book.html","test customer email"]'::jsonb,'["Confirm the Build 259 vehicle-size review migration has been applied in staging.","Create one harmless booking with a model that can be classified confidently and confirm it remains verified.","Create one harmless uncertain/manual vehicle and confirm it is flagged for staff review.","Verify one uncertain booking without changing size and confirm no customer interruption is required.","For another test booking, propose a corrected size/price and send the secure confirmation link.","Open the link as the test customer, confirm the corrected booking, then separately test the cancel outcome with another harmless record.","Verify expired/used tokens cannot be reused."]'::jsonb,'Known vehicles stay verified, uncertain vehicles enter review, staff can accept or propose a correction, and the one-time customer link can confirm or cancel safely.','/admin-booking.html','vehicle_size_review_259',260,true),
('media-health-260',42,'Media and public proof','high','Accept database-first Media Health and a bounded public-delivery sample','Media Health should summarize the managed library cheaply and only perform a small explicit delivery sample. It must not fan out hundreds of public URL probes during page load.','["/admin-media-health.html","/admin-photo-studio.html","Cloudflare Workers Logs"]'::jsonb,'["Open Media Health and confirm the managed-library summary loads without a deep public scan.","Review missing alt text, large files, unassigned images, missing storage identity and duplicate candidates.","Use the Photo Studio links from a few flagged items and confirm they select or locate the correct asset.","Run the explicit public-delivery sample and confirm it checks only the bounded sample shown in the interface.","Confirm normal page load and summary refresh do not produce subrequest-limit or 1102 errors."]'::jsonb,'Media Health is current with Photo Studio, normal load is database-first, and the explicit delivery sample is bounded and actionable.','/admin-media-health.html','media_health_260',260,true),
('daip-project-flow-260',43,'DAIP and media','high','Accept the normal fresh DAIP project workflow and governance boundaries','Creative Projects is the normal starting point for new DAIP work. Intake Dry Run is only a fictional validation rehearsal and Gate C is a governance/technical evidence gate, not a per-project publishing button.','["/admin-creative-projects.html","/admin-daip-media.html","/admin-daip-intake-dry-run.html","/admin-daip-gate-c.html"]'::jsonb,'["Create one harmless Creative Project using the Start fresh DAIP project guidance.","Open private DAIP Media Intake for that project and confirm raw media remains private.","Use Intake Dry Run separately with fictional metadata to confirm validation/rejection rules without uploading a real file.","Open Gate C and confirm it records technical/governance review evidence only and remains held unless the broader gate criteria are deliberately satisfied.","Return to the Creative Project and confirm consent/content-package review remains separate from raw-media intake."]'::jsonb,'Staff can explain and follow Create Project → private raw intake → review/content package, while Dry Run and Gate C are used only for their intended validation/governance purposes.','/admin-creative-projects.html','daip_project_flow_260',260,true),
('quote-pipeline-259',44,'Leads and fleet','high','Accept the editable quote pipeline and booking hand-off','Fleet and custom-service leads need an actionable quote workspace rather than a read-only dashboard.','["/admin-quotes.html","/fleet.html","/admin-booking.html"]'::jsonb,'["Create or select one harmless quote row.","Edit customer, town, scope, quoted amount, probability, source, follow-up stage and follow-up date.","Save and refresh to confirm the shared database record persists.","Link a harmless booking where appropriate and use Open booking dashboard.","Confirm mobile/tablet controls remain usable and no quote action silently changes an unrelated booking."]'::jsonb,'A quote can be selected, edited, saved, followed up and deliberately linked to a booking with clear shared state.','/admin-quotes.html','quote_pipeline_259',260,true)
on conflict (process_key) do update set sort_order=excluded.sort_order,category=excluded.category,severity=excluded.severity,title=excluded.title,why_text=excluded.why_text,locations=excluded.locations,instructions=excluded.instructions,done_when=excluded.done_when,action_route=excluded.action_route,evidence_key=excluded.evidence_key,source_build=excluded.source_build,is_active=true,updated_at=now();

insert into public.app_launch_readiness_evidence(evidence_key,title,detail,severity,status,sort_order) values
('deploy_260','Build 260 deployment/cache parity','Verify current Pages/Functions deployment, Startup assets, UI scanner and service-worker cache all report Build 260.','block','pending',45),
('photo_sync_260','Photo Studio bounded sync','Verify approved-folder R2 sync, multi-placement assignment, and one-location reset-to-default without Worker subrequest errors.','warn','pending',46),
('vehicle_size_review_259','Vehicle-size review flow','Verify known-size booking, uncertain-size review, corrected price link, confirm/cancel and one-time token behaviour.','block','pending',47),
('media_health_260','Database-first Media Health','Verify managed-library diagnostics load cheaply and the optional public-delivery sample remains bounded.','warn','pending',48),
('daip_project_flow_260','Fresh DAIP project workflow','Verify Creative Projects is the normal start, private intake stays private, Dry Run is fictional, and Gate C is governance-only.','warn','pending',49),
('quote_pipeline_259','Editable quote pipeline','Verify a quote can be selected, edited, followed up and deliberately handed to booking.','warn','pending',50)
on conflict (evidence_key) do update set title=excluded.title,detail=excluded.detail,severity=excluded.severity,sort_order=excluded.sort_order,updated_at=now();

update public.app_roadmap_execution_items set is_current_cycle=false where coalesce(is_current_cycle,false)=true;
insert into public.app_roadmap_execution_items(item_key,title,workstream,priority,status,target_build,sort_order,source_document,cycle_key,is_current_cycle,action_path) values
('b260_01','Deploy Build 260 and prove cache/script/service-worker parity','reliability','critical','planned',260,10,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-startup-guide.html#ui-health'),
('b260_02','Apply outstanding Build 259 vehicle-size and Build 260 startup migrations in staging','reliability','critical','planned',260,20,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-startup-guide.html#blockers'),
('b260_03','Accept bounded Photo Studio R2 sync, multi-placement and reset-to-default','media','critical','planned',260,30,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-photo-studio.html'),
('b260_04','Accept database-first Media Health and bounded delivery sample','media','high','planned',260,40,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-media-health.html'),
('b260_05','Run one fresh Creative Project through the clarified private DAIP start flow','daip','high','planned',260,50,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-creative-projects.html'),
('b260_06','Accept editable Quote Pipeline and booking hand-off','operations','high','planned',260,60,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-quotes.html'),
('b260_07','Accept uncertain vehicle-size staff review and customer confirm/cancel flow','booking','critical','planned',260,70,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-booking.html'),
('b260_08','Complete booking, deposit, final-balance, refund and webhook production acceptance','payments','critical','planned',260,80,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-startup-guide.html#production'),
('b260_09','Verify external email/SMS delivery and failure/retry evidence','reliability','critical','planned',260,90,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-startup-guide.html#production'),
('b260_10','Complete transactional inventory posting, idempotency, shortage and reversal acceptance','operations','critical','planned',260,100,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-inventory-posting.html'),
('b260_11','Finish catalog publish-readiness, supplier repair and sellable-item image review','operations','high','planned',260,110,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-catalog.html'),
('b260_12','Finish deliberate public photo assignments, contextual alt text and local proof review','media','high','planned',260,120,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-photo-studio.html'),
('b260_13','Complete owner-editable add-on landing content, pricing caveats and process explanations','seo','high','planned',260,130,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-content.html'),
('b260_14','Populate Gallery with approved before/after, evidence, technique and efficiency proof','media','high','planned',260,140,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-photo-studio.html'),
('b260_15','Complete real-device CSS/mobile acceptance on booking, pricing, services, maintenance and fleet','reliability','critical','planned',260,150,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-ui-health.html'),
('b260_16','Complete keyboard, focus, label, contrast and reduced-motion accessibility review','customer','high','planned',260,160,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-ui-health.html'),
('b260_17','Verify Search Console, sitemap/canonicals/schema and Google Business Profile evidence','seo','high','planned',260,170,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-seo-tasks.html'),
('b260_18','Perform Supabase restore rehearsal and Cloudflare deployment rollback drill','reliability','critical','planned',260,180,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-startup-guide.html#blockers'),
('b260_19','Implement/accept the private DAIP processing consumer, retry/dead-letter and reviewed derivatives path','daip','high','planned',260,190,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-daip-media.html'),
('b260_20','Run controlled invite-only soft launch with monitoring, incident and daily evidence review','operations','critical','planned',260,200,'MASTER_VALUE_ROADMAP.md','build260',true,'/admin-startup-guide.html')
on conflict (item_key) do update set title=excluded.title,workstream=excluded.workstream,priority=excluded.priority,status=case when public.app_roadmap_execution_items.status='done' then 'done' else excluded.status end,target_build=excluded.target_build,sort_order=excluded.sort_order,source_document=excluded.source_document,cycle_key=excluded.cycle_key,is_current_cycle=true,action_path=excluded.action_path,updated_at=now();
