-- Build 195 schema/history/template/export preview pass — 2026-06-06
-- No database schema changes are required for this pass.
-- Build 195 reuses app_management_settings and app_management_setting_history for:
--   * field-level editable-setting validation markers
--   * selected-history side-by-side diffs
--   * settings audit export
--   * fallback-backed setting reports
--   * media-requirement compare/diff preview
-- It also reuses existing bookings, booking_events, notification_events, and document rendering helpers for:
--   * policy version stamping on customer-facing booking documents
--   * booking business-hours/holiday override reason logging
--   * invoice/appointment confirmation template preview and dry-run test-send payloads
-- Apply no DDL for Build 195; deploy the updated Functions, HTML, JSON validation schema, and Markdown docs.
