-- Build 187 local-page water-rule visibility note.
-- No DDL is required for this pass.
-- Purpose:
--   * Re-verify Oxford/Tillsonburg, Woodstock/Oxford, and Norfolk seasonal outdoor water-use restrictions.
--   * Force verified water-rule notes into public town landing pages and the public landing-page API fallback.
--   * Keep DB/Admin App content from hiding corrected local-page water guidance before a service-area rules re-import.
--
-- Operational follow-up:
--   Re-import data/service_area_rules.json into Supabase service_area_rules/app_management_settings
--   after deployment so DB rows match the bundled Build 187 fallback.
