-- Build 169 auth and analytics fallback note — 2026-05-23
-- No new destructive DDL is required for this pass.
-- Runtime changes:
-- - /api/admin/auth_me and /api/client/auth_me now return a 200 signed-out/degraded response instead of a raw 500 when auth storage/config is unavailable.
-- - /api/analytics/ingest now fails open with ok/skipped instead of a raw 500 when analytics storage is unavailable.
-- - Login endpoints return JSON application errors instead of raw 500s for config/schema/hash/runtime issues.
-- Operational check before testing login:
-- - confirm SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set in Cloudflare Pages production/preview variables;
-- - confirm public.staff_users, public.staff_auth_sessions, public.customer_profiles, public.customer_auth_sessions, and public.site_activity_events exist;
-- - if an account has a bcrypt password_hash and bcryptjs is not bundled, re-run auth_bootstrap_admin_password with hash_mode='sha256' or add bcryptjs to the Pages build.
