-- Build 141 service-area/water-rule fallback note
-- Date: 2026-05-14
-- No DDL required for this pass.
--
-- Runtime/data changes:
-- - Added data/service_area_rules.json as the shared JSON fallback for Norfolk/Oxford towns,
--   water-use reminders, official county links, and county fallback behavior.
-- - Expanded data/rosie_services_pricing_and_packages.json service_areas.
-- - Made the booking service-area field typeable with county fallback resolution.
-- - Expanded Admin App service-area editing fields.
--
-- Recommended next DB step:
-- CREATE TABLE service_area_rules (...) or store this content in app_management_settings
-- as a canonical service_area_rules key, then keep data/service_area_rules.json as fallback.
