-- Build 143 public catalog fallback merge note
-- Date: 2026-05-15
--
-- No database DDL is required for this pass.
--
-- Context:
-- The public Consumables page was showing only the two edited DB rows because
-- the page returned the Supabase catalog feed as soon as it found any rows.
-- The public Gear page had the same possible failure mode.
--
-- Resolution:
-- Public catalog pages now merge DB rows over the bundled JSON fallback catalogs:
--   - data/rosie_products_catalog.json for consumables
--   - data/systems_catalog.json for gear/tools
--
-- This keeps saved DB edits visible without hiding the unedited bundled
-- fallback catalog before the full DB migration/import is complete.
