-- Build 183 — direct provider refund initiation, reconciliation export, webhook warning dashboard, and IMAGES.md refresh.
-- No DDL required.
-- Depends on Build 180, 181, and 182 payment tables/columns:
--   public.quote_deposit_payment_requests
--   public.quote_payment_webhook_events
--   public.quote_deposit_refund_records
-- New APIs added in this build use those existing tables:
--   /api/admin/quote_deposit_refund_initiate
--   /api/admin/payment_reconciliation_export
--   /api/admin/payment_webhook_warnings_summary
-- The image requirements refresh is documentation/data-only and does not require SQL changes.
