-- Build 178 — Conversion status, saved price review, public content rendering, privacy badges, and proof recommendations.
-- No new DDL is required in this pass.
-- Depends on Build 175 lead_conversion_drafts/site_content_blocks and Build 177 final_price_review fields.
-- New endpoints added:
--   /api/admin/lead_conversion_status_save
--   /api/admin/lead_conversion_price_review_save
-- Existing final price fields used:
--   lead_conversion_drafts.final_price_review
--   lead_conversion_drafts.final_price_status
--   lead_conversion_drafts.final_price_total_cents
--   lead_conversion_drafts.final_deposit_cents
--   lead_conversion_drafts.final_price_reviewed_at
