// Build 268 — thin, event-driven Rosie Dazzlers service worker.
// Only the shared launcher shell is precached. Business modules/workflows remain lazy.
const CACHE='rosie-app-v20260829build268';
const URLS=['/','/app/','/app/customer/','/assets/site.css','/assets/app-core/module-shell.css','/assets/app-core/module-resolver.js','/assets/app-core/module-navigation.js','/assets/app-core/install-client.js','/apps/launcher/app-launcher.js','/assets/admin-auth.js','/assets/admin-shell.js','/manifest.webmanifest','/assets/app-icons/rosie-192.png','/assets/app-icons/rosie-512.png','/assets/app-icons/rosie-maskable-512.png'];
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);await Promise.allSettled(URLS.map(async(url)=>{try{const response=await fetch(url,{cache:'reload'});if(response.ok)await cache.put(url,response.clone());}catch{}}));await self.skipWaiting();})());});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;event.respondWith((async()=>{const url=new URL(event.request.url),sameOrigin=url.origin===self.location.origin,isApi=sameOrigin&&url.pathname.startsWith('/api/');const cached=async()=>sameOrigin&&!isApi?await caches.match(event.request,{ignoreSearch:true}):null;try{const response=await fetch(event.request);if(response.status>=500&&sameOrigin&&!isApi){const found=await cached();if(found)return found;}if(response.ok&&sameOrigin&&!isApi){const destination=event.request.destination||'';if(['document','script','style','image','font','manifest'].includes(destination)||event.request.mode==='navigate'){const clone=response.clone();event.waitUntil(caches.open(CACHE).then(cache=>cache.put(event.request,clone)).catch(()=>null));}}return response;}catch{const found=await cached();if(found)return found;if(event.request.mode==='navigate'){const shell=await caches.match('/');if(shell)return shell;}return new Response('Rosie Dazzlers is temporarily offline and this resource is not cached.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}});}})());});
// Push is event-driven. Remote delivery is not active until subscriptions/server delivery are configured.
self.addEventListener('push',event=>{let payload={};try{payload=event.data?event.data.json():{};}catch{payload={body:event.data?.text?.()||''};}const title=String(payload.title||'Rosie Dazzlers');const options={body:String(payload.body||'You have a Rosie Dazzlers update.'),tag:String(payload.tag||'rosie-update'),renotify:payload.renotify===true,data:{url:String(payload.url||'/app/')},icon:'/assets/app-icons/rosie-192.png',badge:'/assets/app-icons/rosie-192.png'};event.waitUntil(self.registration.showNotification(title,options));});
self.addEventListener('notificationclick',event=>{event.notification.close();const requested=String(event.notification?.data?.url||'/app/');const safeUrl=requested.startsWith('/')?requested:'/app/';event.waitUntil((async()=>{const windows=await clients.matchAll({type:'window',includeUncontrolled:true});for(const client of windows){if('focus'in client){await client.focus();if('navigate'in client)await client.navigate(safeUrl);return;}}if(clients.openWindow)await clients.openWindow(safeUrl);})());});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});