-- Build 148: landing photos and add-on landing-page media/process completeness
-- Date: 2026-05-16
-- No DDL required in this pass.
--
-- This pass stores regional-photo and add-on landing-page media details in existing
-- landing page JSON/app-setting structures and fallback files:
--   data/landing_regional_photos.json
--   functions/api/landing_pages_public.js
--
-- Future DB migration direction:
--   landing_pages table with draft/published JSON fields
--   media_library table for URL, source, consent/license, alt text, caption, and related location/service
--   landing_page_media join table for hero/gallery/process images
