#!/usr/bin/env node
import assert from "node:assert/strict";
import { buildRecoveryExportOperationalProof } from "../functions/api/_lib/recovery-export-operational-proof.js";
import { buildRecoveryAuthenticatedDeviceObservationExecutionEvidence } from "../functions/api/_lib/recovery-authenticated-device-observation-execution-evidence.js";
const proof=buildRecoveryExportOperationalProof({launch_evidence:[{evidence_key:"backups",status:"verified",verified_at:"2026-09-25T10:00:00Z",evidence_note:"Owner observed backup snapshot artifact retained in offsite R2 bucket."},{evidence_key:"rollback_drill",status:"verified",verified_at:"2026-09-25T10:10:00Z",evidence_note:"Owner operator observed bounded non-Production recovery drill in staging using backup artifact snapshot reference and retained R2 bucket; recovery completed successfully with no deviations."}],generated_at:"2026-09-25T12:00:00Z"});
for(const key of ["observed","bounded_nonproduction_scope_explicit","observer_role_present","backup_reference_present","retention_reference_present","outcome_recorded","abort_or_deviation_recorded"])assert.equal(proof.recovery_drill[key],true,key);
assert.equal(proof.recovery_drill.outcome_classification,"successful");
assert.equal(proof.recovery_drill.evidence_note_exposed,false);
const recovery={recovery_export_operational_proof:proof,refresh_closure_review:{status:"retain_hold_closure_review_required",evidence_traceability:{evidence_trace_key:"backup:current|retention:current|drill:current"},rows:[{id:"backup_artifact",source_available:true,observed_at:"2026-09-25T10:00:00Z",freshness:"current",classification:"owner_action_observed"},{id:"retention_location",source_available:true,observed_at:"2026-09-25T10:00:00Z",freshness:"current",classification:"owner_action_observed"},{id:"recovery_drill",source_available:true,observed_at:"2026-09-25T10:10:00Z",freshness:"current",classification:"owner_action_observed"}]},validation_drill_decision_readiness:{status:"operator_recovery_decision_ready"}};
const role=(id,at,devices,browsers,route,width)=>({id,current_observation:true,current_pass:true,current_regression:false,observed_at:at,authentication_evidence_present:true,browser_evidence_present:true,route_evidence_present:true,viewport_evidence_present:true,outcome_evidence_present:true,outcome_successful:true,outcome_regression_present:false,device_classes:devices,browser_classes:browsers,routes:[route],viewport_widths:[width]});
const device={observation_refresh_regression_triage:{status:"current_observation_review_ready"},roles:[role("customer","2026-09-25T10:20:00Z",["desktop"],["chrome"],"/book",1440),role("detailer","2026-09-25T10:21:00Z",["phone"],["safari"],"/app/detailer/",390),role("operations","2026-09-25T10:22:00Z",["tablet"],["chrome"],"/app/operations/",1024),role("admin","2026-09-25T10:23:00Z",["desktop"],["edge"],"/admin-today.html",1366)]};
const ready=buildRecoveryAuthenticatedDeviceObservationExecutionEvidence({recovery,authenticated_device:device,continuity:{status:"bounded_continuity_review_ready"},generated_at:"2026-09-25T12:00:00Z"});
assert.equal(ready.execution_evidence_build,500);
assert.equal(ready.status,"execution_evidence_review_ready");
assert.equal(ready.recovery.status,"bounded_nonproduction_execution_observation_recorded");
assert.equal(ready.recovery.post_observation_requirements_complete,true);
assert.equal(ready.authenticated_device.status,"current_authenticated_observation_execution_evidence_recorded");
assert.deepEqual(ready.authenticated_device.current_role_ids,["customer","detailer","operations","admin"]);
assert.deepEqual(ready.authenticated_device.observed_device_ids,["desktop","phone","tablet"]);
assert.equal(ready.separation_rules.recovery_and_device_populations_joined,false);
assert.equal(ready.truth_boundary.recovery_drill_executed_by_this_build,false);
const regressionDevice=structuredClone(device); regressionDevice.observation_refresh_regression_triage.status="regression_triage_required"; regressionDevice.roles[1].current_pass=false; regressionDevice.roles[1].current_regression=true;
assert.equal(buildRecoveryAuthenticatedDeviceObservationExecutionEvidence({recovery,authenticated_device:regressionDevice}).status,"authenticated_device_regression_observed");
const incompleteDevice=structuredClone(device); incompleteDevice.roles=incompleteDevice.roles.filter(row=>row.id!=="operations");
const incomplete=buildRecoveryAuthenticatedDeviceObservationExecutionEvidence({recovery,authenticated_device:incompleteDevice});
assert.equal(incomplete.status,"authenticated_device_observation_execution_evidence_incomplete");
assert.deepEqual(incomplete.authenticated_device.refresh_required_device_ids,["tablet"]);
const noNonprod=structuredClone(recovery); noNonprod.recovery_export_operational_proof.recovery_drill.bounded_nonproduction_scope_explicit=false;
assert.equal(buildRecoveryAuthenticatedDeviceObservationExecutionEvidence({recovery:noNonprod,authenticated_device:device}).recovery.status,"bounded_nonproduction_scope_not_explicit");
const unavailable=buildRecoveryAuthenticatedDeviceObservationExecutionEvidence({recovery:{refresh_closure_review:{status:"blocked_source_unavailable",rows:[]},validation_drill_decision_readiness:{status:"retain_hold_unavailable_source"}},authenticated_device:{observation_refresh_regression_triage:{status:"unavailable"},roles:[]}});
assert.equal(unavailable.status,"execution_evidence_source_unavailable");
assert.equal(unavailable.truth_boundary.canonical_hold_mutated,false);
console.log("BUILD 500 RECOVERY DRILL & AUTHENTICATED DEVICE OBSERVATION EXECUTION EVIDENCE TEST: PASS");
