#!/usr/bin/env node
import assert from "node:assert/strict";
import { buildWinterBookingQuoteRuleControlledActivationDecision } from "../functions/api/_lib/winter-booking-quote-rule-controlled-activation-decision.js";
import { buildWinterBookingQuoteRuleOutcomeFreshnessReview } from "../functions/api/_lib/winter-booking-quote-rule-outcome-freshness-review.js";

const common={capability_evidence_current:true,owner_review_decision:"approve_public_claim_review",owner_reviewed_at:"2026-09-26T11:00:00-04:00",owner_review_reference:"owner-review-496",activation_readiness_owner_decision:"approve_activation_readiness_review",activation_reviewed_at:"2026-09-26T11:10:00-04:00",activation_review_reference:"owner-review-497",public_claim_activation_decision:"approve_public_claim_activation",public_claim_activation_reviewed_at:"2026-09-26T11:20:00-04:00",public_claim_activation_reference:"owner-review-506",public_claim_activation_wording_confirmed:true};
const rows=[
{...common,package_code:"interior",classification:"cold_snap_capable",evidence_source_type:"process",evidence_source:"interior-process",booking_rule_candidate:"allow_with_current_conditions_check",quote_rule_candidate:"quote_with_current_conditions_disclosure",winter_rule_customer_transparency_confirmed:true,winter_rule_controlled_activation_decision:"approve_controlled_activation",winter_rule_controlled_activation_reviewed_at:"2026-09-26T11:30:00-04:00",winter_rule_controlled_activation_reference:"owner-507-interior",winter_rule_controlled_activation_outcome:"activated",winter_rule_controlled_activation_outcome_observed_at:"2026-09-29T09:00:00-04:00",winter_rule_controlled_activation_outcome_reference:"outcome-517-interior",winter_rule_applied_booking_rule:"allow_with_current_conditions_check",winter_rule_applied_quote_rule:"quote_with_current_conditions_disclosure",winter_rule_availability_revalidated:true,winter_rule_checkout_collision_revalidated:true,winter_rule_runtime_revalidated_at:"2026-09-30T09:00:00-04:00",winter_rule_runtime_revalidation_reference:"runtime-517-interior"},
{...common,package_code:"premium_wash",classification:"temperature_limited_outdoor",evidence_source_type:"product",evidence_source:"wash-tds",minimum_working_temperature_c:5,exact_temperature_claim_supported:true,booking_rule_candidate:"temperature_limited_current_conditions_check",quote_rule_candidate:"quote_with_source_owned_temperature_limit",winter_rule_customer_transparency_confirmed:true,winter_rule_controlled_activation_decision:"hold_controlled_activation",winter_rule_controlled_activation_reviewed_at:"2026-09-26T11:35:00-04:00",winter_rule_controlled_activation_reference:"owner-507-wash",winter_rule_controlled_activation_outcome:"retain_hold",winter_rule_controlled_activation_outcome_observed_at:"2026-09-29T09:10:00-04:00",winter_rule_controlled_activation_outcome_reference:"hold-517-wash",winter_rule_availability_revalidated:true,winter_rule_checkout_collision_revalidated:true,winter_rule_runtime_revalidated_at:"2026-09-30T09:10:00-04:00",winter_rule_runtime_revalidation_reference:"runtime-517-wash"},
{...common,add_on_code:"ceramic",classification:"controlled_environment_required",evidence_source_type:"site",evidence_source:"ceramic-site",indoor_capable_workflow_supported:true,indoor_workflow_source_type:"process",indoor_workflow_reference:"ceramic-indoor",controlled_environment_site_supported:true,controlled_environment_site_reference:"qualified-bay",booking_rule_candidate:"controlled_environment_only",quote_rule_candidate:"quote_for_controlled_environment_only",winter_rule_customer_transparency_confirmed:true,winter_rule_controlled_activation_decision:"approve_controlled_activation",winter_rule_controlled_activation_reviewed_at:"2026-09-26T11:40:00-04:00",winter_rule_controlled_activation_reference:"owner-507-ceramic",winter_rule_controlled_activation_outcome:"activated",winter_rule_controlled_activation_outcome_observed_at:"2026-08-01T09:20:00-04:00",winter_rule_controlled_activation_outcome_reference:"outcome-517-ceramic",winter_rule_applied_booking_rule:"controlled_environment_only",winter_rule_applied_quote_rule:"quote_for_controlled_environment_only",winter_rule_availability_revalidated:true,winter_rule_checkout_collision_revalidated:true,winter_rule_runtime_revalidated_at:"2026-09-30T09:20:00-04:00",winter_rule_runtime_revalidation_reference:"runtime-517-ceramic"},
{...common,add_on_code:"wax",classification:"temperature_limited_outdoor",evidence_source_type:"product",evidence_source:"wax-tds",minimum_working_temperature_c:5,exact_temperature_claim_supported:true,booking_rule_candidate:"temperature_limited_current_conditions_check",quote_rule_candidate:"quote_with_source_owned_temperature_limit",winter_rule_customer_transparency_confirmed:true,winter_rule_controlled_activation_decision:"approve_controlled_activation",winter_rule_controlled_activation_reviewed_at:"2026-09-26T11:45:00-04:00",winter_rule_controlled_activation_reference:"owner-507-wax",winter_rule_controlled_activation_outcome:"activated",winter_rule_controlled_activation_outcome_observed_at:"2026-09-30T09:30:00-04:00",winter_rule_controlled_activation_outcome_reference:"outcome-517-wax",winter_rule_applied_booking_rule:"allow_with_current_conditions_check",winter_rule_applied_quote_rule:"quote_with_source_owned_temperature_limit",winter_rule_availability_revalidated:true,winter_rule_checkout_collision_revalidated:true,winter_rule_runtime_revalidated_at:"2026-09-30T09:30:00-04:00",winter_rule_runtime_revalidation_reference:"runtime-517-wax"},
{...common,add_on_code:"polish",classification:"controlled_environment_required",evidence_source_type:"site",evidence_source:"polish-site",indoor_capable_workflow_supported:true,indoor_workflow_source_type:"process",indoor_workflow_reference:"polish-indoor",controlled_environment_site_supported:true,controlled_environment_site_reference:"qualified-bay",booking_rule_candidate:"controlled_environment_only",quote_rule_candidate:"quote_for_controlled_environment_only",winter_rule_customer_transparency_confirmed:true,winter_rule_controlled_activation_decision:"approve_controlled_activation",winter_rule_controlled_activation_reviewed_at:"2026-09-26T11:50:00-04:00",winter_rule_controlled_activation_reference:"owner-507-polish",winter_rule_controlled_activation_outcome:"activated",winter_rule_controlled_activation_outcome_observed_at:"2026-09-30T09:40:00-04:00",winter_rule_controlled_activation_outcome_reference:"outcome-517-polish",winter_rule_applied_booking_rule:"controlled_environment_only",winter_rule_applied_quote_rule:"quote_for_controlled_environment_only",winter_rule_availability_revalidated:true,winter_rule_checkout_collision_revalidated:false,winter_rule_runtime_revalidated_at:"2026-09-30T09:40:00-04:00",winter_rule_runtime_revalidation_reference:"runtime-517-polish"}
];
const economics={totals:{booking_count:0,ready_booking_count:0,review_booking_count:0,unavailable_booking_count:0,cogs_variance_booking_count:0},rows:[],seasonal_operability_evidence:{rows}};
const pre=buildWinterBookingQuoteRuleControlledActivationDecision({economics});
for(const source of rows){const code=source.package_code||source.add_on_code||source.service_code;const retained=pre.economics.winter_booking_quote_controlled_activation_decision.rows.find(row=>row.code===code);source.winter_rule_outcome_customer_transparency_wording=retained?.customer_limitation_text||"";}
const report=buildWinterBookingQuoteRuleOutcomeFreshnessReview({economics,generated_at:"2026-10-01T12:00:00-04:00",freshness_window_days:30});
const review=report.economics.winter_booking_quote_rule_outcome_freshness_review;
assert.equal(report.winter_booking_quote_outcome_freshness_build,527);
assert.equal(report.winter_booking_quote_outcome_freshness_authority,"winter_booking_quote_rule_outcome_freshness_review");
assert.equal(review.row_count,5); assert.equal(review.counts.current,2); assert.equal(review.counts.controlled_activation_current,1);
assert.equal(review.counts.retain_hold_current,1); assert.equal(review.counts.stale,1); assert.equal(review.counts.rule_or_wording_drift,1);
assert.equal(review.counts.runtime_safety_review,1); assert.equal(review.counts.review_required,3);
assert.equal(review.rows.find(r=>r.code==="interior")?.freshness_state,"controlled_activation_current");
assert.equal(review.rows.find(r=>r.code==="premium_wash")?.freshness_state,"retain_hold_current");
assert.equal(review.rows.find(r=>r.code==="ceramic")?.freshness_state,"stale_outcome_review_required");
assert.equal(review.rows.find(r=>r.code==="wax")?.freshness_state,"applied_rule_drift_review_required");
assert.equal(review.rows.find(r=>r.code==="polish")?.freshness_state,"runtime_safety_revalidation_required");
assert.equal(review.weather_ineligible_sessions_excluded_from_ordinary_conversion_interpretation,true);
assert.equal(report.boundaries.automatic_rule_activation_allowed,false);
assert.equal(report.boundaries.canonical_hold_mutation_allowed,false);
assert.equal(report.truth_boundary.rule_state_may_be_inferred_from_source_or_runtime_green,false);
console.log("BUILD 527 WINTER BOOKING & QUOTE RULE OUTCOME FRESHNESS REVIEW TEST: PASS");
