-- Build 239 — unified Startup Command Center, database-backed process catalog, shared evidence expansion, and current execution cycle.
begin;
create table if not exists public.app_startup_process_items (
 id uuid primary key default gen_random_uuid(),
 process_key text not null unique check (process_key ~ '^[a-z0-9_-]{4,120}$'),
 sort_order integer not null check (sort_order between 1 and 10000),
 category text not null check (char_length(category) between 3 and 120),
 severity text not null check (severity in ('blocker','high','planned')),
 title text not null check (char_length(title) between 5 and 240),
 why_text text not null check (char_length(why_text) between 8 and 3000),
 locations jsonb not null default '[]'::jsonb check (jsonb_typeof(locations)='array'),
 instructions jsonb not null default '[]'::jsonb check (jsonb_typeof(instructions)='array'),
 done_when text not null check (char_length(done_when) between 8 and 3000),
 action_route text null check (action_route is null or char_length(action_route)<=500),
 evidence_key text null check (evidence_key is null or evidence_key ~ '^[a-z0-9_:-]{4,80}$'),
 source_build integer not null default 239 check (source_build between 237 and 999),
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.app_startup_process_audit (
 id uuid primary key default gen_random_uuid(),
 process_key text not null,
 event_type text not null check (event_type in ('seeded','updated','activated','retired')),
 actor_staff_email text null,
 safe_note text not null check (char_length(safe_note) between 3 and 1000),
 created_at timestamptz not null default now()
);
insert into public.app_startup_process_items(process_key,sort_order,category,severity,title,why_text,locations,instructions,done_when,action_route,evidence_key,source_build,is_active) values
('deploy-239',1,'Deployment and CSS','blocker','Deploy Build 239 and verify the unified Startup Command Center','Build 239 consolidates Startup, Launch Readiness, Production Readiness, guided testing, and roadmap execution into one protected interface. A partial or cached deployment could leave old standalone pages or mismatched assets active.','["Cloudflare Pages → Deployments → preview branch", "/admin-startup-guide", "/admin-launch-readiness", "/admin-production", "/admin-test-centre", "Browser DevTools → Network and Console"]'::jsonb,'["Deploy Build 239 to the preview/development branch.", "Open /admin-startup-guide in a private browser window and press Ctrl+Shift+R.", "Confirm the Overview, Blockers, Evidence, Production, Guided Tests, and Roadmap sections all load.", "Open /admin-launch-readiness, /admin-production, and /admin-test-centre and confirm each forwards to the matching Startup Command Center section.", "In DevTools Network, confirm /assets/site.css, AdminShell, AdminMenu, the startup catalog API, and readiness APIs return HTTP 200 or show a clearly labelled fallback.", "Repeat the check at phone width and confirm the section navigation, cards, tables, dialogs, and action buttons remain usable."]'::jsonb,'The unified Startup Command Center is the only normal prelaunch workspace, legacy readiness routes forward safely, all sections work on desktop and mobile, and no required CSS/script/API request fails.','/admin-startup-guide.html','deploy_239',239,true),
('migration-237',2,'Database migrations','blocker','Apply the Build 237 database migration','Shared launch evidence and the current roadmap cycle cannot persist until the new tables/columns exist. The UI has a safe local/static fallback, but shared evidence is the intended source of truth.','["Supabase Dashboard → SQL Editor", "sql/2026-07-28_build237_css_startup_evidence_roadmap.sql", "Supabase Dashboard → Table Editor"]'::jsonb,'["Open the SQL file from the build package.", "Copy the complete file into Supabase SQL Editor.", "Run it in staging/preview first.", "Confirm app_launch_readiness_evidence and app_launch_readiness_evidence_audit exist.", "Confirm app_roadmap_execution_items includes cycle_key, is_current_cycle and action_path.", "Open /admin-launch-readiness and /admin-roadmap-execution and confirm database-backed results load."]'::jsonb,'The two pages report shared/database evidence rather than browser-only fallback and the current Build 237 roadmap cycle appears.','/admin-launch-readiness.html','migration_237',239,true),
('migration-238',3,'Database migrations','blocker','Apply the Build 238 inventory transaction and merge migration','The new Inventory Workbench deliberately refuses to execute bulk changes or duplicate merges without database functions that validate the whole operation and record audit evidence. This prevents a browser/network failure from leaving half a batch changed.','["Supabase Dashboard → SQL Editor", "sql/2026-07-30_build238_inventory_transactions_merge_seo_preflight.sql", "Supabase Dashboard → Database → Functions", "/admin-inventory-manager.html"]'::jsonb,'["Confirm the Build 237 migration has already been applied.", "Open sql/2026-07-30_build238_inventory_transactions_merge_seo_preflight.sql from the build package.", "Copy the complete migration into Supabase SQL Editor and run it in staging/preview first.", "Confirm catalog_inventory_change_batches, catalog_inventory_change_batch_rows and catalog_inventory_merge_audit exist.", "Confirm admin_catalog_inventory_bulk_update and admin_catalog_inventory_merge appear under database functions.", "Reload /admin-inventory-manager.html and preview a harmless batch without executing it.", "Open Transaction & merge history and confirm it loads an empty or current shared audit view without a migration-required error.", "Record the migration date and staging result in Launch Readiness evidence."]'::jsonb,'Both new RPC functions can complete dry-run previews, the three audit tables exist, Transaction & merge history loads, and no browser sequential partial-save fallback is used.','/admin-inventory-manager.html','migration_238',239,true),
('migration-239',4,'Database migrations','blocker','Apply the Build 239 unified Startup Command Center migration','The detailed startup catalog should have one database source of truth instead of being duplicated across JSON, Markdown, launch-readiness cards, production checks, and roadmap notes. The static catalog remains only as a safe read-only fallback.','["Supabase Dashboard → SQL Editor", "sql/2026-08-01_build239_unified_startup_command_center.sql", "Supabase Dashboard → Table Editor → app_startup_process_items", "/admin-startup-guide.html"]'::jsonb,'["Confirm the Build 237 and Build 238 migrations have been applied.", "Open sql/2026-08-01_build239_unified_startup_command_center.sql from the build package.", "Run the complete migration in staging/preview first.", "Confirm app_startup_process_items and app_startup_process_audit exist.", "Confirm the table contains every current blocker and no Build 238 blocker was removed.", "Reload /admin-startup-guide.html and confirm the source badge says Shared database catalog instead of Packaged fallback.", "Change one evidence status, one guided test result, and one roadmap row; refresh on another browser/device and confirm the shared state remains."]'::jsonb,'The Startup Command Center loads every detailed process from the database, all existing items remain present, shared evidence/tests/roadmap persist across devices, and the static JSON is used only during migration or outage.','/admin-startup-guide.html#overview','migration_239',239,true),
('block-calendar',5,'Booking and scheduling','blocker','Retest the repaired Block Calendar against public booking','Availability mistakes can cause double-booking or hide valid dates. A visual repair alone is not enough; save/remove behaviour must be proven against the public booking wizard.','["/admin-blocks.html", "/book", "Supabase schedule block tables"]'::jsonb,'["Choose a future date with no customer booking.", "Create a full-day block and refresh the calendar.", "Open /book in another tab and confirm that date is unavailable.", "Remove the full-day block and confirm the date returns.", "Create an AM-only block and confirm PM remains available.", "Remove AM, create PM-only, and confirm AM remains available.", "Remove the test block and record the tested date in Launch Readiness evidence."]'::jsonb,'Full-date, AM and PM changes persist after refresh and the public booking wizard matches every admin change.','/admin-blocks.html','block_calendar',239,true),
('booking-e2e',6,'Booking and scheduling','blocker','Complete one end-to-end booking test','The complete path must work as one system: availability, vehicle, package, add-ons, customer details, deposit, confirmation and admin record.','["/book", "/admin-booking.html", "Customer confirmation email/inbox"]'::jsonb,'["Use a clearly labelled test customer and a future test date.", "Complete every booking step on a phone-sized screen.", "Confirm pricing, HST/deposit and selected options before payment.", "Finish the booking and save the confirmation number.", "Open Admin Booking and verify date, slot, vehicle, package, add-ons, customer and payment state.", "Cancel or mark the test record according to your test-data policy."]'::jsonb,'The customer and admin views agree and no manual database correction is needed.','/book','booking_e2e',239,true),
('stripe-live',7,'Payments','blocker','Complete and refund a small live Stripe payment','Test-mode success does not prove live keys, webhook secrets, receipts, refunds or accounting evidence are configured correctly.','["/admin-payments.html", "Stripe Dashboard → Payments", "Stripe Dashboard → Developers → Webhooks", "/admin-accounting.html"]'::jsonb,'["Confirm the deployment intentionally reports Stripe live mode.", "Create a small real payment tied to a labelled test booking/quote.", "Confirm the browser returns to the correct success page.", "Verify the Stripe event reached the deployed webhook with HTTP 2xx.", "Verify the payment appears in admin payment/accounting views.", "Issue a full refund and confirm the refund event and final status.", "Record only safe payment identifiers; never put card details in evidence notes."]'::jsonb,'Payment, webhook, receipt, refund and accounting views agree on the final state.','/admin-payments.html','stripe_live',239,true),
('email-delivery',8,'Notifications','blocker','Verify every required email reaches an external inbox','A successful API response does not prove customers or staff receive messages, and spam/mobile formatting failures can block operations.','["/admin-notifications.html", "Notification provider dashboard", "External Gmail/Outlook inboxes"]'::jsonb,'["Send a booking confirmation to an external test inbox.", "Send payment/deposit, staff assignment and consent/review messages where applicable.", "Check Inbox, Promotions and Spam/Junk folders.", "Open each message on desktop and mobile.", "Verify links go to the correct deployed domain and are not expired.", "Record provider message IDs or timestamps without including private content."]'::jsonb,'All required messages arrive, render clearly and contain working links.','/admin-notifications.html','email_delivery',239,true),
('environment',9,'Deployment and security','blocker','Audit Cloudflare production variables and bindings','Missing or preview-only variables are a common cause of login, payment, notification, storage and API failures after launch.','["Cloudflare Dashboard → Workers & Pages → rosiedazzlers → Settings", "docs/CLOUDFLARE_ENVIRONMENT_CHECKLIST.md", "/api/health"]'::jsonb,'["Open Variables and Secrets for both Preview and Production.", "Verify Supabase URL/service key, Stripe keys/webhook secret, notification credentials, R2 bindings and public asset settings.", "Confirm secrets are stored as encrypted secrets, not committed files.", "Confirm custom domains point to the production deployment.", "Open /api/health and record the non-secret environment/mode result.", "Update the environment checklist with the exact Cloudflare screen where each setting lives."]'::jsonb,'Every required integration has an intentional production value/binding and no secret is stored in the repository.','/admin-production.html','environment',239,true),
('backup-restore',10,'Recovery','blocker','Test backup and restore, not just backup availability','A backup is useful only when you know how to restore it and confirm permissions/data integrity afterward.','["Supabase Dashboard → Database → Backups", "/admin-recovery.html", "docs/PRODUCTION_TEST_GUIDE.md"]'::jsonb,'["Confirm the Supabase plan and backup retention available to the project.", "Choose a safe staging restore method or export a small representative data set.", "Restore to a staging project/schema or re-import selected test records.", "Compare row counts and key relationships.", "Test staff access and RLS through Cloudflare Functions after restore.", "Write the exact recovery sequence, owner and expected maximum data-loss window."]'::jsonb,'A documented rehearsal proves data can be recovered and accessed through the application boundary.','/admin-recovery.html','backups',239,true),
('legal',11,'Policies and customer trust','blocker','Review all policies before accepting unrestricted orders','Booking, deposits, cancellations, driveway requirements, runoff/bylaw responsibility, media use and privacy must be clear before a customer commits.','["/privacy.html", "/terms.html", "/refund-policy.html", "/book", "Footer policy links"]'::jsonb,'["Read each policy as a customer, not as a developer.", "Confirm business name, contact method, province and effective date.", "Align cancellation/deposit/refund wording with the actual payment workflow.", "Confirm photo/media consent is optional and visibility choices are clear.", "Confirm power/water, driveway and local bylaw/service-condition wording matches operations.", "Have a qualified Ontario professional review any wording that carries legal or tax risk.", "Verify all policy links are visible from booking, checkout and footer."]'::jsonb,'Published policy wording matches real operations and every checkout/booking link is easy to find.','/privacy.html','legal',239,true),
('security',12,'Deployment and security','blocker','Verify staff permissions, sessions and protected APIs','Admin pages and APIs contain customer, payment and operational data. Visual hiding is not authorization.','["/admin-security.html", "/admin-app.html", "Browser DevTools", "Supabase Security Advisor"]'::jsonb,'["Test Admin, Senior Detailer and Detailer accounts separately.", "Confirm each role can access only intended pages/actions.", "Call protected APIs while signed out and confirm 401/403 responses.", "Sign out and confirm old pages cannot continue saving data.", "Review Supabase Security Advisor and RLS posture.", "Verify security headers on public and admin responses.", "Record failures as blockers, not accepted warnings."]'::jsonb,'Server-side authorization, session expiry/logout and database containment are proven for each role.','/admin-security.html','security',239,true),
('mobile',13,'Mobile and accessibility','high','Complete real-device mobile testing','Responsive browser resizing does not fully test touch, on-screen keyboards, camera uploads, slow connections or mobile payment handoff.','["Real phone browsers", "/book", "/admin-blocks.html", "/admin-inventory-manager.html", "/detailer-jobs.html"]'::jsonb,'["Test portrait and landscape on a real phone.", "Open/close the mobile dropdown menu on every core page.", "Complete booking fields with the on-screen keyboard.", "Test calendar tapping, inventory row/card editing and image upload/capture.", "Confirm no horizontal page drift except intentional table/calendar scroll regions.", "Test a slower network profile and retry behaviour.", "Capture screenshots of any overlap or unreadable control."]'::jsonb,'All primary customer and staff tasks can be completed without zooming, clipped controls or lost input.','/admin-test-centre.html','mobile',239,true),
('accessibility',14,'Mobile and accessibility','high','Complete keyboard, focus, labels and contrast review','Accessible forms reduce customer abandonment and also expose hidden UI/JavaScript problems before launch.','["Public home/services/booking/payment pages", "Critical admin pages", "Browser accessibility tree"]'::jsonb,'["Navigate every interactive control using Tab/Shift+Tab only.", "Confirm visible focus never disappears behind sticky elements.", "Verify each input has a useful label and each error is announced/readable.", "Check heading order and confirm one H1 per exposed page.", "Check colour contrast for text, buttons, notices and disabled states.", "Test at 200% browser zoom.", "Document exceptions with route, control and screenshot."]'::jsonb,'Critical flows are usable by keyboard and at high zoom with clear labels, focus and errors.','/admin-test-centre.html','accessibility',239,true),
('search-preflight',15,'SEO and local visibility','high','Complete Search Console, sitemap, canonical and schema preflight','The site already has strong local/service architecture, but indexing and structured-data evidence must be checked on the deployed canonical domain.','["Google Search Console", "/sitemap.xml", "Google Rich Results Test", "Public page source"]'::jsonb,'["Verify the rosiedazzlers.ca Search Console property.", "Submit https://rosiedazzlers.ca/sitemap.xml.", "Inspect the homepage, booking, primary service and town URLs.", "Confirm canonical URLs use the production domain and preferred trailing-slash pattern.", "Test LocalBusiness/Service/WebSite structured data and correct errors.", "Review indexed pages for accidental admin/dev URLs.", "Record real search queries monthly before rewriting titles."]'::jsonb,'The sitemap is accepted, important pages are inspectable/indexable, admin pages are noindex and schema has no critical errors.','/admin-seo-tasks.html','search',239,true),
('business-profile',16,'SEO and local visibility','high','Complete and align Google Business Profile','Local visibility depends heavily on accurate relevance, distance/service-area and prominence signals; the profile must match the website and real business.','["Google Business Profile Manager", "/contact.html", "/services.html", "Town/service landing pages"]'::jsonb,'["Confirm the real-world business name without keyword stuffing.", "Choose the most specific accurate primary category and relevant secondary categories.", "Confirm service areas, phone, website and hours.", "Add accurate services and descriptions that match the site.", "Upload approved real photos regularly.", "Create a review-request link and respond to reviews.", "Compare profile information with footer/contact/schema data for consistency."]'::jsonb,'The profile is verified, complete, accurate and consistent with the production website.','/admin-marketing.html','business_profile',239,true),
('inventory-cleanup',17,'Inventory and products','high','Clean inventory records before relying on product sales and job costing','Suspicious imported names, missing costs/categories and duplicates reduce customer trust and make pricing/profitability unreliable.','["/admin-inventory-manager.html", "/admin-catalog.html", "Inventory Workbench filters"]'::jsonb,'["Filter Suspicious names and replace ASIN/alphanumeric titles with clear product names.", "Complete category, vendor, unit, cost and reorder point.", "Confirm tool versus consumable classification.", "Archive rows that are true duplicates only after checking history/references.", "Leave unfinished rows inactive/private.", "Export a CSV snapshot before large bulk changes.", "Spot-check calculations after updates."]'::jsonb,'Every active/sellable row has a clear name, classification, category, cost and intentional active/public state.','/admin-inventory-manager.html','inventory_cleanup',239,true),
('product-images',18,'Inventory and products','high','Complete product image sets and metadata','Products need strong visual proof, but multiple images must remain ordered, descriptive, consent-safe and performant.','["/admin-inventory-manager.html", "/admin-catalog.html", "Product public page/gallery"]'::jsonb,'["Set one featured image that clearly shows the complete item.", "Add up to seven gallery images covering detail, scale, packaging, use and variations.", "Order images from strongest overview to supporting detail.", "Write concise descriptive alt text rather than keyword lists.", "Record image role, caption, source/provenance and consent where applicable.", "Verify images load on mobile and do not cause layout shift.", "Keep products private until the image set and customer-facing copy are ready."]'::jsonb,'Every sellable product has a reliable featured image, useful gallery and accurate accessible metadata.','/admin-inventory-manager.html','product_images',239,true),
('pricing-tax',19,'Payments','blocker','Verify pricing, deposits, HST and final totals','Customer-visible totals must match booking, checkout, receipts and accounting. Price drift is a launch blocker.','["/pricing.html", "/book", "/admin-site-settings.html", "/admin-tax-review.html", "Stripe checkout"]'::jsonb,'["Compare every package and add-on price in public pricing, booking and admin catalog.", "Verify vehicle-size price differences.", "Confirm deposit rules and cancellation/refund handling.", "Verify HST calculation and rounding on representative totals.", "Confirm Stripe checkout amount matches the final booking/quote.", "Verify receipt and accounting entries use the same amounts.", "Document who can change prices and how changes are reviewed."]'::jsonb,'The same selected service produces the same subtotal, tax, deposit and total everywhere.','/admin-tax-review.html','pricing_tax',239,true),
('analytics',20,'SEO and local visibility','high','Verify analytics and conversion events in production','You need trustworthy evidence before changing SEO, ads or booking UX, and consent settings must be respected.','["/admin-analytics.html", "Browser DevTools", "Analytics provider real-time/debug view"]'::jsonb,'["Accept and reject analytics consent and confirm expected script behaviour.", "Trigger page view, package view, booking start, quote start, booking complete and payment events.", "Confirm events use the production domain and useful non-private parameters.", "Verify UTM/source values flow into lead/booking reporting.", "Exclude internal/admin traffic where practical.", "Record a baseline before launch marketing changes."]'::jsonb,'Core conversion events arrive once, contain no sensitive customer data and can be tied to real acquisition sources.','/admin-analytics.html','analytics',239,true),
('monitoring',21,'Recovery','high','Prepare production monitoring and incident response','During the first live bookings, failures must be noticed quickly and have a clear owner and rollback path.','["/admin-production.html", "Cloudflare logs", "Supabase logs", "Stripe webhook logs", "KNOWN_GAPS_AND_RISKS.md"]'::jsonb,'["Confirm where Cloudflare Function errors are viewed.", "Confirm Supabase database/auth logs and Stripe webhook logs.", "Define who checks failures during the first week and how often.", "Write a stop-taking-bookings procedure.", "Document rollback to the previous deployment.", "Create an incident record for any payment, booking, privacy or data-loss failure.", "Review logs daily during soft launch."]'::jsonb,'A named owner can detect, classify, communicate and roll back a critical failure without searching for instructions.','/admin-production.html','monitoring',239,true),
('soft-launch',22,'Go-live decision','blocker','Use an invite-only soft launch before unrestricted public promotion','A controlled first group gives real evidence without exposing the business to a large volume of simultaneous failures.','["/admin-launch-readiness.html", "/admin-today.html", "/admin-production.html", "Business operations calendar"]'::jsonb,'["Resolve all critical blockers or explicitly document why a controlled exception is safe.", "Invite only a small number of known customers.", "Limit daily capacity to what can be manually supported.", "Review each booking, payment, email, job update, inventory movement and review request.", "Hold public advertising until the first transactions are stable.", "Record incidents and fixes immediately.", "Expand gradually after a defined stable period."]'::jsonb,'Several real transactions complete without critical manual correction and monitoring evidence supports broader launch.','/admin-launch-readiness.html','operations',239,true),
('duplicate-merge',23,'Inventory and products','high','Test the reviewed duplicate inventory merge workflow','Build 238 now provides a preview-first merge that transfers known operational references, records compensating quantity movements and archives the duplicate. It still requires migration and staging proof before use on important rows.','["/admin-inventory-manager.html", "Supabase → catalog_inventory_merge_audit", "Supabase → catalog_inventory_movements", "STARTUP_GO_LIVE_BLOCKERS.md"]'::jsonb,'["Apply the Build 238 migration in staging.", "Choose two harmless test rows that truly represent the same item and have no irreplaceable history.", "Select exactly those two rows in Inventory Workbench and choose Review two-row merge.", "Choose the survivor row and enter a clear reason.", "Select Preview merge and inspect quantity, gallery count and every reference-count card.", "Confirm the survivor should keep its current values when present and inherit only missing values.", "Execute the merge, reload the page and verify the duplicate is inactive, private and zero quantity.", "Verify purchase orders, movements, assignments, service links and project references point to the survivor where applicable.", "Verify catalog_inventory_merge_audit contains before/after rows and the reason.", "Open Transaction & merge history, confirm the merge appears with the correct survivor, archived duplicate, reason, actor, timestamp and transferred-reference counts, then export the audit CSV."]'::jsonb,'A staging merge preserves history, transfers known references, records compensating quantity movements, archives rather than deletes the duplicate, and appears correctly in the read-only audit history/CSV.','/admin-inventory-manager.html','inventory_merge_238',239,true),
('bulk-rpc',24,'Inventory and products','high','Test transactional bulk inventory updates and rollback behaviour','Build 238 replaces sequential browser saves with an all-or-nothing database function. The complete batch is validated before any write and records a batch header plus row-level before/after evidence.','["/admin-inventory-manager.html", "Supabase → catalog_inventory_change_batches", "Supabase → catalog_inventory_change_batch_rows", "Cloudflare Function logs"]'::jsonb,'["Apply the Build 238 migration in staging.", "Select two harmless inventory test rows.", "Choose a bulk field and value and enter a specific audit reason.", "Select Preview batch and verify the message says no rows were changed.", "Choose Apply transaction and confirm both rows change together.", "Verify one batch header and two row evidence records exist.", "Repeat with one deliberately invalid test value and confirm the entire transaction fails with neither row changed.", "Open Transaction & merge history and confirm the successful batch shows the correct operation, row count, reason, actor and timestamp; export the audit CSV.", "Restore the test values through another audited transaction."]'::jsonb,'Valid batches update every selected row together, invalid batches change none, before/after evidence exists for every row, and the committed batch appears correctly in audit history/CSV.','/admin-inventory-manager.html','inventory_bulk_rpc_238',239,true),
('media-derivatives',25,'Media and performance','planned','Generate responsive product/gallery image derivatives','Seven original images can create slow mobile pages and layout instability without standardized dimensions and modern formats.','["R2 derivative worker", "Media Health", "Product/gallery rendering"]'::jsonb,'["Define canonical source-image rules and maximum upload size.", "Generate thumbnail, card, medium and large dimensions.", "Create WebP/AVIF with JPEG/PNG fallback where supported.", "Store width, height, format and byte size metadata.", "Render srcset/sizes and fixed aspect-ratio boxes.", "Keep the original source private or archival according to policy.", "Monitor failed derivative jobs and provide retry."]'::jsonb,'Public product/gallery pages load appropriately sized images with stable layout and fallback formats.','/admin-media-health.html',null,239,true),
('markdown-retirement',26,'Documentation','planned','Retire redundant Markdown only after release guards are modernized','The project has many historical documents. Deleting them now can break release checks or erase evidence, but treating all of them as current creates confusion.','["AI_PROJECT_HANDOFF.md", "MASTER_VALUE_ROADMAP.md", "DOC_INDEX.md", "scripts/release_check.py", "docs/archive"]'::jsonb,'["Treat AI_PROJECT_HANDOFF.md and MASTER_VALUE_ROADMAP.md as the only living direction documents.", "Mark operational/reference documents clearly.", "Map which release checks read historical text markers.", "Replace brittle text-marker guards with current file/route/API tests.", "Move superseded documents into docs/archive rather than deleting them.", "Update DOC_INDEX.md with canonical, operational and archive sections.", "Run the complete release suite after each archive batch."]'::jsonb,'A new developer can find current direction in two files and historical evidence remains available without controlling the roadmap.','/admin-docs.html',null,239,true),
('notification-health',27,'Production communications','blocker','Verify notification provider and delivery-queue health','A configured email webhook is not enough. Queued or failed customer and staff messages can cause missed bookings, payment confusion, and consent failures.','["/admin-startup-guide.html#production", "Cloudflare → Workers & Pages → Settings → Variables", "Notification provider dashboard"]'::jsonb,'["Open the Startup Command Center Production section and refresh the report.", "Confirm the email provider is configured before using Send test.", "Use Check config only first, then send exactly one message to a Rosie-controlled external inbox.", "Confirm the message arrives on desktop and mobile and inspect spam/junk.", "Review failed and queued notification counts; repair the provider or retry path before launch.", "Record the receive time and safe provider result in evidence without storing addresses, secrets, or message content."]'::jsonb,'The provider test succeeds, the controlled inbox receives the message, and failed/queued notification counts are zero or have a documented accepted reason.','/admin-startup-guide.html#production','notification_health',239,true),
('payment-link-operations',28,'Payments','blocker','Verify hosted final-balance links, webhook evidence, and reconciliation','Customers need a dependable way to pay the remaining balance. A checkout URL alone is not proof that payment status, webhook processing, receipt, refund, and accounting records agree.','["/admin-startup-guide.html#production", "Stripe Dashboard → Developers → Webhooks", "/admin-accounting.html"]'::jsonb,'["Create a small internal final-balance request.", "From the Production section, create a hosted checkout link and confirm the amount, currency, branding, and customer reference.", "Complete the test in Stripe test mode first, then perform the separately approved small live-payment test.", "Confirm webhook receipt, payment-request status, receipt, ledger/journal evidence, and customer/admin history agree.", "Issue the planned test refund and confirm the refund appears in Stripe and the application records.", "Record only safe IDs, timestamps, and outcomes in Startup evidence."]'::jsonb,'A hosted link works, payment and refund webhooks are recorded, receipt and accounting evidence agree, and the manual fallback remains available.','/admin-startup-guide.html#production','payment_links',239,true),
('upload-recovery',29,'Field reliability','high','Prove mobile photo/video upload interruption and recovery','Detailing proof and customer updates are captured in the field, where connections can be weak. Silent loss or duplicate media would damage trust and job records.','["/admin-startup-guide.html#tests", "/detailer-jobs.html", "/admin-startup-guide.html#production"]'::jsonb,'["Use a test booking and non-sensitive photo/video on a real phone.", "Upload a small photo and confirm visible progress and completion.", "Begin a short video upload, switch networks or briefly interrupt connectivity, and confirm a useful retry/cancel state appears.", "Restore connectivity and retry once.", "Confirm the final media exists once, has the correct visibility, and any failed session appears in Production readiness for review.", "Record device, browser, connection type, approximate file size, and outcome."]'::jsonb,'Photo and video uploads show progress, interruption produces a recoverable state, retry does not duplicate media, and failed sessions are visible to staff.','/admin-startup-guide.html#tests','upload_recovery',239,true),
('retention-review',30,'Privacy and storage','high','Complete media retention, legal-hold, and cleanup review','Unlimited storage increases cost and privacy exposure, while aggressive deletion could remove proof needed for disputes, taxes, or consent records.','["/admin-startup-guide.html#production", "/admin-media.html", "Supabase/R2 storage dashboards"]'::jsonb,'["Open the Production section and run retention in dry-run mode only.", "Review every candidate by booking, media type, stage, consent, incident/legal-hold status, and retention policy.", "Confirm permanent proof and legal-hold items are excluded.", "Correct any missing policy or expiry date before marking records for review.", "Approve deletion only through the documented storage-cleanup process; do not manually delete referenced objects.", "Record candidate counts, exclusions, reviewer, and date."]'::jsonb,'Dry-run candidates are explainable, protected evidence is excluded, referenced objects are not orphaned, and an approved cleanup/restore procedure is documented.','/admin-startup-guide.html#production','retention_review',239,true),
('incident-closeout',31,'Customer protection','blocker','Verify incident closeout, privacy, and review-request safety','An unresolved issue or private incident note must never be exposed to a customer or followed immediately by an automated review request.','["/admin-startup-guide.html#tests", "/admin-incident-reports.html", "/admin-workflow.html", "Customer progress link in a private browser"]'::jsonb,'["Create a harmless internal test incident on a test booking.", "Confirm staff-only notes and evidence remain hidden from the signed-out customer progress view.", "Publish only specifically approved customer-safe wording.", "Confirm booking closeout or review-request automation is blocked while the incident is unresolved.", "Resolve the test incident with an auditable decision and verify the review workflow follows the documented policy.", "Remove or archive test data according to the test-data policy."]'::jsonb,'Private material never appears to the customer, unresolved incidents block unsafe closeout/review automation, and resolution creates complete audit evidence.','/admin-startup-guide.html#tests','incident_closeout',239,true),
('rollback-drill',32,'Deployment and recovery','blocker','Complete a deployment rollback and incident-response drill','Backups protect data, but a bad frontend/function deployment also needs a fast, rehearsed rollback path with owners and verification steps.','["Cloudflare Pages → Deployments", "/admin-startup-guide.html#production", "STARTUP_GO_LIVE_BLOCKERS.md", "docs/PRODUCTION_TEST_GUIDE.md"]'::jsonb,'["Choose a safe preview deployment and identify the previous known-good deployment.", "Document who can trigger rollback and where the control is located.", "Roll preview back or promote a known-good preview in a controlled rehearsal.", "Verify home, booking, login, Block Calendar, Startup Command Center, payment endpoint health, and database connectivity after rollback.", "Restore the latest build and repeat the smoke check.", "Record timestamps, owner, deployment IDs, observed downtime, and any missing permissions."]'::jsonb,'A named owner can restore a known-good deployment, critical smoke tests pass after rollback, and the written incident path is usable without guessing.','/admin-startup-guide.html#production','rollback_drill',239,true),
('local-proof-cadence',33,'Local SEO and trust','high','Establish an approved local-photo, review, and Business Profile cadence','Local visibility depends on accurate relevance signals and real prominence. Fresh approved work, complete profile information, and legitimate reviews are more valuable than duplicated keyword pages.','["/admin-startup-guide.html#blockers", "Google Business Profile → Photos, Services, Reviews, Performance", "/gallery.html", "/admin-gallery.html", "Search Console"]'::jsonb,'["Confirm the Business Profile name, primary category, service areas, phone, hours, website, and services match the live site and real-world operation.", "Replace the highest-value public placeholders with Rosie-owned, consent-approved before/after work.", "Add descriptive alt text and connect proof to the relevant service/town page without duplicating thin pages.", "Create a repeatable post-job review request that follows Google policy and pauses for unresolved incidents.", "Schedule a weekly profile/photo/review-response check and a monthly Search Console/local landing-page review.", "Record the first completed cycle and the next review date."]'::jsonb,'The profile and website agree, priority pages show authentic approved proof, review requests are policy-safe, and a repeatable local visibility cadence has an owner.','/admin-startup-guide.html#blockers','local_proof_cadence',239,true),
('startup-single-interface',34,'Documentation and operations','high','Retire duplicate preflight navigation and train staff on one Startup Command Center','Even correct checks become unreliable when staff must guess between Startup Guide, Launch Readiness, Production, Guided Tests, and Roadmap pages.','["/admin-startup-guide.html", "Admin Menu", "AI_PROJECT_HANDOFF.md", "STARTUP_GO_LIVE_BLOCKERS.md"]'::jsonb,'["Confirm the Admin Menu has one Startup Command Center entry.", "Confirm old readiness URLs forward to the appropriate Startup section and remain available only for compatibility.", "Update internal instructions, bookmarks, and screenshots to use /admin-startup-guide.html.", "Train each staff role on Overview, Blockers, Evidence, Production, Tests, and Roadmap tabs.", "Confirm permissions allow required staff to view or update only the sections they are authorized to use.", "After one complete test cycle, remove duplicate wording from living documentation while retaining historical release evidence."]'::jsonb,'Staff use one interface for launch work, legacy links forward safely, permissions are correct, and no current document instructs staff to maintain a separate preflight checklist.','/admin-startup-guide.html','startup_single_interface',239,true)
on conflict(process_key) do update set sort_order=excluded.sort_order,category=excluded.category,severity=excluded.severity,title=excluded.title,why_text=excluded.why_text,locations=excluded.locations,instructions=excluded.instructions,done_when=excluded.done_when,action_route=excluded.action_route,evidence_key=excluded.evidence_key,source_build=excluded.source_build,is_active=true,updated_at=now();
insert into public.app_launch_readiness_evidence(evidence_key,title,detail,severity,status,sort_order) values
('deploy_239','Build 239 unified Startup deployment','Deploy Build 239 and verify the single Startup Command Center plus compatibility redirects.','block','pending',1),
('migration_238','Build 238 inventory migration','Apply and verify transactional bulk update, duplicate merge, and inventory audit schema.','block','pending',8),
('migration_239','Build 239 Startup migration','Apply the shared startup process catalog and Build 239 current roadmap cycle.','block','pending',9),
('notification_health','Notification provider and queue health','Verify a controlled external delivery and resolve failed or stuck notification events.','block','pending',32),
('payment_links','Hosted final-balance payment links','Verify checkout, webhook, receipt, refund, and reconciliation evidence agree.','block','pending',33),
('upload_recovery','Mobile upload recovery','Prove interrupted photo/video uploads can recover without silent loss or duplication.','warn','pending',34),
('retention_review','Media retention review','Complete a dry-run retention review with legal-hold and permanent-proof exclusions.','warn','pending',35),
('incident_closeout','Incident closeout and review safety','Verify unresolved incidents protect privacy and block unsafe review requests.','block','pending',36),
('rollback_drill','Deployment rollback drill','Rehearse a known-good Cloudflare rollback and critical-route smoke check.','block','pending',37),
('local_proof_cadence','Local proof and review cadence','Establish a recurring approved-photo, Business Profile, review-response, and Search Console routine.','warn','pending',38),
('startup_single_interface','Single Startup Command Center','Confirm staff use one interface and legacy readiness routes only forward to it.','warn','pending',39)
on conflict(evidence_key) do update set title=excluded.title,detail=excluded.detail,severity=excluded.severity,sort_order=excluded.sort_order,updated_at=now();
update public.app_roadmap_execution_items set is_current_cycle=false where cycle_key<>'build239';
insert into public.app_roadmap_execution_items(item_key,title,workstream,priority,status,target_build,sort_order,source_document,cycle_key,is_current_cycle,action_path) values
('b239_01','Deploy Build 239 and verify the unified Startup Command Center','reliability','critical','in_progress',239,1,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Deploy preview, hard-refresh /admin-startup-guide, verify every section, then confirm legacy readiness URLs forward to the correct anchor.'),
('b239_02','Apply the Build 239 startup catalog and roadmap migration in staging','reliability','critical','planned',239,2,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Run sql/2026-08-01_build239_unified_startup_command_center.sql, refresh schema cache, and confirm the shared database catalog source badge.'),
('b239_03','Complete Build 237 and Build 238 migration verification if outstanding','reliability','critical','planned',239,3,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Verify evidence, roadmap, inventory transaction, merge, and audit tables/RPCs exist before production.'),
('b239_04','Retest Block Calendar full-day, AM, and PM behaviour','booking','critical','planned',239,4,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Create/remove each block type and confirm public booking availability matches after refresh.'),
('b239_05','Complete end-to-end booking and admin reconciliation','booking','critical','planned',239,5,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Run a phone-sized test booking and reconcile customer, booking, calendar, deposit, and staff records.'),
('b239_06','Verify Stripe checkout, webhook, refund, and accounting evidence','payments','critical','planned',239,6,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Complete test-mode and approved small live transactions, then reconcile webhook, receipt, refund, and journal evidence.'),
('b239_07','Verify notification provider and clear failed/queued events','reliability','critical','planned',239,7,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Run config-only then one controlled external delivery; resolve failed or stuck events before launch.'),
('b239_08','Audit Cloudflare variables, bindings, domains, and rollback access','reliability','critical','planned',239,8,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Compare preview/production variables, verify R2/Supabase/Stripe bindings, and identify the rollback owner and known-good deployment.'),
('b239_09','Perform Supabase restore and Cloudflare rollback rehearsals','reliability','critical','planned',239,9,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Restore safe staging data, rehearse deployment rollback, and run critical smoke checks after each recovery action.'),
('b239_10','Publish and link legal, refund, cancellation, cookie, and media policies','customer','critical','planned',239,10,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Review final wording and confirm booking, checkout, customer portal, and footer links are visible and consistent.'),
('b239_11','Complete real-device mobile and accessibility acceptance testing','reliability','high','planned',239,11,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Test customer/admin critical paths on real devices plus keyboard, focus, labels, contrast, errors, and touch targets.'),
('b239_12','Prove weak-network media upload retry and deduplication','media','high','planned',239,12,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Interrupt a test photo/video upload, retry once, and confirm visible recovery with no duplicate or public exposure.'),
('b239_13','Complete incident privacy and review-request safety test','customer','critical','planned',239,13,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Verify staff-only incident content stays private and unresolved incidents block unsafe closeout/review requests.'),
('b239_14','Complete retention dry-run and legal-hold exclusion review','media','high','planned',239,14,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Review candidates, confirm protected evidence exclusions, and document cleanup/restore ownership.'),
('b239_15','Clean inventory names, categories, costs, duplicates, and audit history','operations','high','planned',239,15,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Use suspicious-name, merge-preview, transactional bulk-update, and history tools; preserve referenced records.'),
('b239_16','Complete sellable product gallery, pricing, HST, and publish readiness','operations','high','planned',239,16,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Finish featured plus gallery images, metadata, costs, price/tax totals, stock, policies, and public display checks.'),
('b239_17','Submit sitemap and validate canonicals, structured data, and index coverage','seo','high','planned',239,17,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Use Search Console and Rich Results testing; correct inconsistent canonicals, noindex, schema, or sitemap entries.'),
('b239_18','Align Google Business Profile and establish local proof cadence','seo','high','planned',239,18,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Verify profile facts, add approved local proof, respond to reviews, and schedule weekly/monthly checks.'),
('b239_19','Run invite-only soft launch with daily command-centre review','operations','critical','planned',239,19,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Accept a small known-customer cohort and inspect every booking, payment, notification, upload, incident, inventory, and log event.'),
('b239_20','Modernize release guards and retire duplicate readiness/Markdown navigation','documentation','medium','planned',239,20,'STARTUP_GO_LIVE_BLOCKERS.md','build239',true,'Replace stale text-marker dependencies, archive superseded docs safely, and keep the Startup Command Center plus three authority documents current.')
on conflict(item_key) do update set title=excluded.title,workstream=excluded.workstream,priority=excluded.priority,status=case when public.app_roadmap_execution_items.status='done' then 'done' else excluded.status end,target_build=excluded.target_build,sort_order=excluded.sort_order,source_document=excluded.source_document,cycle_key=excluded.cycle_key,is_current_cycle=true,action_path=excluded.action_path,updated_at=now();
create index if not exists app_startup_process_active_order_idx on public.app_startup_process_items(is_active,sort_order);
create index if not exists app_startup_process_category_idx on public.app_startup_process_items(category,severity,sort_order);
create index if not exists app_startup_process_audit_idx on public.app_startup_process_audit(process_key,created_at desc);
alter table public.app_startup_process_items enable row level security;
alter table public.app_startup_process_audit enable row level security;
revoke all privileges on table public.app_startup_process_items,public.app_startup_process_audit from public,anon,authenticated;
grant all privileges on table public.app_startup_process_items,public.app_startup_process_audit to service_role;
comment on table public.app_startup_process_items is 'Build 239 canonical detailed Startup Command Center process catalog. Database is primary; packaged JSON is read-only outage/migration fallback.';
comment on table public.app_startup_process_audit is 'Build 239 audit history for controlled startup-process catalog changes. Do not store secrets or private customer content.';
commit;
