-- Build 157 - Social API publish bridge no-DDL note
-- Purpose: document that Build 157 adds direct/API publishing code paths and UI controls
-- without changing the database shape introduced in Build 156.
--
-- No schema changes are required if Build 156 social queue migration has already been run.
--
-- Build 157 uses the existing tables:
--   public.social_channels
--   public.social_post_queue
--   public.social_dispatch_attempts
--
-- Recommended Cloudflare Pages environment variables for direct/API attempts:
--   X_ACCESS_TOKEN
--   FACEBOOK_PAGE_ID
--   FACEBOOK_PAGE_ACCESS_TOKEN
--   INSTAGRAM_BUSINESS_ACCOUNT_ID
--   INSTAGRAM_ACCESS_TOKEN or META_PAGE_ACCESS_TOKEN
--   META_GRAPH_VERSION (optional; defaults in code)
--   SOCIAL_DISPATCH_WEBHOOK_URL (optional automation fallback)
--   SOCIAL_DISPATCH_WEBHOOK_SECRET (optional shared secret for automation fallback)
--
-- TikTok, Google Business Profile, LinkedIn, YouTube Shorts, and future networks should
-- continue through webhook/manual fallback until their OAuth/app approval flows are complete.
select 'Build 157 social API publish bridge has no database DDL changes.' as build157_note;
