-- Build 193 social template endpoint and editable-setting validation note (2026-06-05)
-- No database schema changes are required for this pass.
--
-- This build fixes /api/admin/social_templates_list so omitted platform/service_area
-- filters and fallback rows with null platform values cannot throw a null.toLowerCase()
-- error. It also adds safer Admin Social fallback rendering when template options
-- are unavailable, plus bundled field-level validation schemas for editable site
-- settings. The validation uses the existing app_management_settings and
-- app_management_setting_history tables from Build 189/190.
--
-- Existing schema dependencies:
-- - app_management_settings
-- - app_management_setting_history
-- - social_caption_templates (optional; fallback templates remain available)
-- - social_hashtag_presets (optional; fallback presets remain available)
