-- Build 137 local SEO / admin inventory / media-source pass
-- Date: 2026-05-09
-- No DDL is required for this pass.
--
-- What changed in code/docs:
-- - Restored the admin add-on image hydration and landing helper fixes from the dev build.
-- - Restored Admin Catalog bundled inventory fallback merging so saved DB rows do not hide unsaved gear/consumable fallback rows.
-- - Added data/local_seo_targets.json and scripts/local_seo_audit.py so town/service search targets can be checked during every pass.
-- - Added data/sample_reviews.json as a temporary review-content source until the real review API is connected.
-- - Added/updated IMAGES.md with exact media sizes and replacement workflow guidance.
-- - Refreshed sitemap.xml with lastmod/changefreq/priority values for priority public routes.
--
-- Existing schema still expected for full feature coverage:
-- - app_management_settings for pricing catalog, landing pages, and shared dropdown option settings.
-- - catalog_inventory_items for DB-backed gear/consumable inventory.
-- - site_activity_events for diagnostics/analytics where available.
