-- Build 192 editable operations completion note
-- Date: 2026-06-05
-- No new tables or columns are required for this pass.
-- This build reuses existing app_management_settings and app_management_setting_history rows for:
--   business_profile, site_policies, document_templates, business_hours_holidays,
--   navigation_footer, option_libraries, analytics_event_registry, media_requirements,
--   landing_pages_content.
-- Operationally, Build 192 adds structured admin editors, restore-from-history UI,
-- analytics-registry warning checks, media requirement sync/restore controls, and
-- business-hours/holiday warnings around public/admin booking slot selection.
