-- Build 173 Admin Content Center — FAQ editor bridge
-- Date: 2026-05-24
-- Purpose: no new database table is required for Build 173.
-- The new Admin Content Center reads and writes the Build 172 table:
--   public.public_faq_entries
--
-- Required migration before using the editor:
--   sql/2026-05-24_build172_public_faq_content_foundation.sql
--
-- Build 173 API endpoints:
--   /api/admin/content_faqs_list
--   /api/admin/content_faqs_save
--
-- This file is intentionally a no-DDL schema-tracking note so the build history,
-- SUPABASE_SCHEMA.sql, and DATABASE_STRUCTURE_CURRENT.md all remain synchronized.
