-- Build 200 friendly pricing editor completion pass
-- Date: 2026-06-09
--
-- No database schema changes are required for this pass.
--
-- Admin App package detail fields, live chart previews, and the dashboard
-- advanced-JSON reminder card continue to use existing app_management_settings
-- payloads and bundled JSON fallbacks. The pricing_catalog row remains the
-- canonical DB-backed authority for packages, add-ons, service areas,
-- requirements, booking rules, and chart helpers.
