import {requireStaffAccess,json} from '../_lib/staff-auth.js';
import {serviceReady,rest,clean,jsonBody,OUTPUT_TYPES} from '../_lib/creative-projects.js';
const uuid=v=>/^[0-9a-f-]{36}$/i.test(String(v||''));
export async function onRequest(c){
 if(c.request.method==='OPTIONS')return cors(new Response('',{status:204}));
 if(c.request.method!=='POST')return cors(json({ok:false,error:'Method not allowed.'},405));
 const a=await requireStaffAccess({request:c.request,env:c.env,capability:'manage_staff',allowLegacyAdminFallback:true});if(!a.ok)return cors(a.response);
 if(!serviceReady(c.env))return cors(json({ok:false,error:'Supabase service configuration is missing.'},503));
 const b=await jsonBody(c.request),projectId=clean(b.project_id,80),action=clean(b.action,60),email=clean(a.actor?.email,200)||null;
 if(!uuid(projectId))return cors(json({ok:false,error:'Valid project is required.'},400));
 try{
  let event='updated',safe='Advanced project record updated.';
  if(action==='save_financials'){
   const patch={project_classification:clean(b.project_classification,30)||'commercial',expected_revenue_cad:Number(b.expected_revenue_cad||0),actual_revenue_cad:Number(b.actual_revenue_cad||0),profitability_note:clean(b.profitability_note,2000)||null,consent_expires_at:b.consent_expires_at||null,consent_reminder_days:Math.max(1,Math.min(365,Number(b.consent_reminder_days||30))),updated_at:new Date().toISOString(),updated_by_staff_email:email};
   await rest(c.env,`creative_projects?id=eq.${encodeURIComponent(projectId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(patch)});safe='Profitability, classification, and consent reminder settings updated.';
  } else if(action==='session_story_approval'){
   if(!uuid(b.session_id))throw new Error('Valid session is required.');
   const approved=Boolean(b.approved);await rest(c.env,`creative_project_sessions?id=eq.${encodeURIComponent(b.session_id)}&project_id=eq.${encodeURIComponent(projectId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({approved_for_story:approved,story_approved_at:approved?new Date().toISOString():null,story_approved_by_staff_email:approved?email:null})});event='session_story_approval';safe=`Session ${approved?'approved for':'removed from'} story generation.`;
  } else if(action==='inventory_reservation'){
   const row={project_id:projectId,material_line_id:uuid(b.material_line_id)?b.material_line_id:null,inventory_item_id:b.inventory_item_id,quantity:Number(b.quantity||0),unit:clean(b.unit,40)||'item',status:clean(b.status,20)||'draft',review_note:clean(b.review_note,1200)||null,created_by_staff_email:email,updated_at:new Date().toISOString(),inventory_mutated:false};
   if(!uuid(row.inventory_item_id)||row.quantity<=0)throw new Error('Inventory item id and quantity are required.');
   if(row.status==='reviewed'){row.reviewed_by_staff_email=email;row.reviewed_at=new Date().toISOString();}
   if(row.status==='posted'){row.reviewed_by_staff_email=email;row.reviewed_at=new Date().toISOString();row.posted_by_staff_email=email;row.posted_at=new Date().toISOString();}
   await rest(c.env,'creative_project_inventory_reservations',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});event='inventory_reservation_updated';safe=`Project consumption ledger saved as ${row.status}; ordinary inventory was not mutated.`;
  } else if(action==='shot_plan'){
   await rest(c.env,'creative_project_shot_plan_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({project_id:projectId,shot_type:clean(b.shot_type,30)||'other',description:clean(b.description,500),required:Boolean(b.required),status:clean(b.status,30)||'planned',consent_required:Boolean(b.consent_required),safe_note:clean(b.safe_note,1200)||null})});event='shot_plan_updated';safe='Before/after shot-plan item saved.';
  } else if(action==='learning_item'){
   const status=clean(b.status,30)||'draft';await rest(c.env,'creative_project_learning_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({project_id:projectId,item_type:clean(b.item_type,30)||'lesson',title:clean(b.title,180),detail:clean(b.detail,4000),status,score:b.score===''||b.score==null?null:Math.max(0,Math.min(100,Number(b.score))),rationale:clean(b.rationale,2000)||null,approved_by_staff_email:status==='approved'?email:null,approved_at:status==='approved'?new Date().toISOString():null,created_by_staff_email:email})});event='learning_updated';safe=`${clean(b.item_type,30)||'lesson'} saved as ${status}.`;
  } else if(action==='generate_content_plan'){
   const sessions=await rest(c.env,`creative_project_sessions?select=session_type,summary,mistakes_and_fixes,next_action,started_at&project_id=eq.${encodeURIComponent(projectId)}&approved_for_story=eq.true&order=started_at.asc`);
   if(!sessions?.length)throw new Error('Approve at least one session for story generation first.');
   const project=(await rest(c.env,`creative_projects?select=title,purpose,outcome_summary,lessons_learned,future_recommendations,consent_status,before_after_applicability&id=eq.${encodeURIComponent(projectId)}&limit=1`))?.[0];
   const outline=sessions.map((s,i)=>`${i+1}. ${s.session_type}: ${s.summary}${s.mistakes_and_fixes?`\n   Challenge/fix: ${s.mistakes_and_fixes}`:''}${s.next_action?`\n   Next: ${s.next_action}`:''}`).join('\n');
   const platforms=Array.isArray(b.output_types)?b.output_types.filter(x=>OUTPUT_TYPES.includes(x)):['youtube_video','youtube_shorts','instagram_reels','tiktok','facebook_video','pinterest_pins','etsy_draft','website_product_page','educational_article'];
   for(const output_type of platforms){const vertical=['youtube_shorts','instagram_reels','tiktok','facebook_video'].includes(output_type);const planning={source:'approved_sessions',session_count:sessions.length,youtube_chapters:output_type==='youtube_video'?sessions.map((s,i)=>({order:i+1,title:s.summary.slice(0,80)})):[],clip_plan:vertical?sessions.slice(0,5).map((s,i)=>({order:i+1,hook:s.summary.slice(0,120),duration_seconds:15})):[],pinterest_plan:output_type==='pinterest_pins'?{board:'Rosie Dazzlers Projects',pin_angles:['process','result','lesson']}:null,etsy_fields:output_type==='etsy_draft'?{attributes_pending:true,shipping_profile_pending:true}:null,website_plan:output_type==='website_product_page'?{schema_type:'Product',internal_links:['services','gallery','booking']}:null};
    await rest(c.env,'creative_project_output_drafts',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({project_id:projectId,output_type,draft_kind:output_type==='etsy_draft'||output_type==='website_product_page'?'commerce_copy':output_type==='educational_article'?'report_outline':'story_outline',hook:`${project?.title||'Project'}: ${sessions[0].summary.slice(0,180)}`,outline,caption:`Documented from ${sessions.length} approved project session${sessions.length===1?'':'s'}.`,call_to_action:'Review the full process and verified result.',seo_title:(project?.title||'Creative project').slice(0,180),seo_description:(project?.purpose||project?.outcome_summary||sessions[0].summary).slice(0,500),aspect_ratio:vertical?'9:16':output_type==='pinterest_pins'?'2:3':'16:9',review_status:'draft',planning_data:planning,safety_review_status:output_type==='educational_article'?'required':'not_reviewed',updated_by_staff_email:email,updated_at:new Date().toISOString()})});}
   event='content_plan_generated';safe=`Rule-based draft plans generated from ${sessions.length} approved sessions for ${platforms.length} outputs.`;
  } else if(action==='archive_export'){
   const [project,sessions,outputs,materials,labour,costs,learning]=await Promise.all([rest(c.env,`creative_projects?select=*&id=eq.${encodeURIComponent(projectId)}&limit=1`),rest(c.env,`creative_project_sessions?select=*&project_id=eq.${encodeURIComponent(projectId)}`),rest(c.env,`creative_project_outputs?select=*&project_id=eq.${encodeURIComponent(projectId)}`),rest(c.env,`creative_project_material_lines?select=*&project_id=eq.${encodeURIComponent(projectId)}&is_deleted=eq.false`),rest(c.env,`creative_project_labour_lines?select=*&project_id=eq.${encodeURIComponent(projectId)}&is_deleted=eq.false`),rest(c.env,`creative_project_cost_lines?select=*&project_id=eq.${encodeURIComponent(projectId)}&is_deleted=eq.false`),rest(c.env,`creative_project_learning_items?select=*&project_id=eq.${encodeURIComponent(projectId)}`)]);
   const manifest={version:'build231',generated_at:new Date().toISOString(),project:project?.[0]||null,sessions,outputs,materials,labour,costs,learning,media_bytes_included:false,public_destination_enabled:false};
   await rest(c.env,'creative_project_archive_exports',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({project_id:projectId,manifest,contains_media_bytes:false,public_destination_enabled:false,created_by_staff_email:email})});event='archive_export_prepared';safe='Metadata-only project archive manifest prepared.';
  } else if(action==='template_save'){
   const row={template_key:clean(b.template_key,80),name:clean(b.name,120),project_type:clean(b.project_type,30)||'other',purpose_prompt:clean(b.purpose_prompt,2000)||null,audience_prompt:clean(b.audience_prompt,800)||null,default_before_after_applicability:clean(b.default_before_after_applicability,30)||'not_reviewed',safe_instructions:clean(b.safe_instructions,4000)||null,active:Boolean(b.active),updated_by_staff_email:email,updated_at:new Date().toISOString()};
   await rest(c.env,'creative_project_templates',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});event='template_updated';safe=`Project template ${row.template_key} saved.`;
  } else return cors(json({ok:false,error:'Unknown advanced project action.'},400));
  await rest(c.env,'creative_project_audit',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({project_id:projectId,event_type:event,actor_staff_email:email,safe_note:safe})});return cors(json({ok:true,message:safe}));
 }catch(e){return cors(json({ok:false,error:e.message},500))}
}
function cors(r){const h=new Headers(r.headers);h.set('Access-Control-Allow-Origin','*');h.set('Access-Control-Allow-Methods','POST,OPTIONS');h.set('Access-Control-Allow-Headers','Content-Type,x-admin-password,x-staff-email,x-staff-user-id');h.set('Cache-Control','no-store');return new Response(r.body,{status:r.status,headers:h})}
