import {requireStaffAccess,json} from '../_lib/staff-auth.js';
import {bucketFor,serviceReady,rest,jsonBody,clean} from '../_lib/daip-media.js';
export async function onRequest(context){
  if(context.request.method==='OPTIONS')return new Response('',{status:204}); if(context.request.method!=='POST')return json({ok:false,error:'Method not allowed.'},405);
  const auth=await requireStaffAccess({request:context.request,env:context.env,capability:'manage_staff',allowLegacyAdminFallback:true});if(!auth.ok)return auth.response;
  if(!serviceReady(context.env))return json({ok:false,error:'Supabase service configuration is missing.'},503); const {bucket}=bucketFor(context.env);if(!bucket)return json({ok:false,error:'Private DAIP R2 binding is not configured.'},503);
  const body=await jsonBody(context.request),sessionId=clean(body.session_id,80);if(!/^[0-9a-f-]{36}$/i.test(sessionId))return json({ok:false,error:'Valid session_id is required.'},400);
  try{const session=(await rest(context.env,`daip_media_upload_sessions?select=*&id=eq.${encodeURIComponent(sessionId)}&limit=1`))?.[0];if(!session)return json({ok:false,error:'Upload session not found.'},404);if(session.status==='uploaded')return json({ok:false,error:'Completed raw originals cannot be aborted or deleted from this intake screen.'},409);await bucket.resumeMultipartUpload(session.object_key,session.multipart_upload_id).abort();const now=new Date().toISOString();await rest(context.env,`daip_media_upload_sessions?id=eq.${encodeURIComponent(sessionId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'aborted',aborted_at:now,updated_at:now})});await rest(context.env,`daip_project_media_assets?id=eq.${encodeURIComponent(session.asset_id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({upload_status:'aborted',updated_at:now})});await rest(context.env,'creative_project_audit',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({project_id:session.project_id,event_type:'media_upload_aborted',actor_staff_email:String(auth.actor?.email||'').slice(0,200)||null,safe_note:'Incomplete private DAIP multipart upload aborted.'})}).catch(()=>{});return json({ok:true,message:'Incomplete multipart upload aborted. Raw originals that already completed are not deleted.'});}catch(error){return json({ok:false,error:error.message||'Could not abort upload.'},500)}
}
